name: CI
on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
